from pydantic import BaseModel
from typing import Optional, Any
from datetime import datetime
from uuid import UUID

class QueryLog(BaseModel):
    # IDs
    id: str  # Local UUID from extension
    session_id: str # Generated by background.js per session
    
    # Query Info
    query_id: Optional[int] = None
    query_name: Optional[str] = None
    query_text: Optional[str] = None
    user_intent: Optional[str] = None
    
    # Execution Info
    execution_id: Optional[str] = None
    execution_succeeded: bool
    runtime_seconds: Optional[int] = None
    
    # Error Info
    error_message: Optional[str] = None
    error_type: Optional[str] = None
    error_line: Optional[int] = None
    error_column: Optional[int] = None
    
    # Fix Info
    has_fix: bool = False
    fix_execution_id: Optional[str] = None
    fixed_query: Optional[str] = None
    
    # Dataset Metadata
    training_pair_type: Optional[str] = None # "successful_query" | "error_correction"
    
    # Timestamps
    timestamp: datetime
    created_at: Optional[datetime] = None
    updated_at: Optional[datetime] = None

class SyncRequest(BaseModel):
    session_id: str
    logs: list[QueryLog]
